// ------------------------------------------------------------------------------
// <auto-generated>
//    Generated by avrogen, version 1.7.7.5
//    Changes to this file may cause incorrect behavior and will be lost if code
//    is regenerated
// </auto-generated>
// ------------------------------------------------------------------------------
namespace AvroTypes.v1
{
	using System;
	using System.Collections.Generic;
	using System.Text;
	using global::Avro;
	using global::Avro.Specific;
	
	public partial class Exception : ISpecificRecord
	{
		public static Schema _SCHEMA = Schema.Parse(@"{""type"":""record"",""name"":""Exception"",""namespace"":""AvroTypes.v1"",""fields"":[{""name"":""StackTrace"",""type"":[""null"",""string""]},{""name"":""Source"",""type"":[""null"",""string""]},{""name"":""Message"",""type"":[""null"",""string""]},{""name"":""HResult"",""type"":""int""},{""name"":""HelpLink"",""type"":[""null"",""string""]}]}");
		private string _StackTrace;
		private string _Source;
		private string _Message;
		private int _HResult;
		private string _HelpLink;
		public virtual Schema Schema
		{
			get
			{
				return Exception._SCHEMA;
			}
		}
		public string StackTrace
		{
			get
			{
				return this._StackTrace;
			}
			set
			{
				this._StackTrace = value;
			}
		}
		public string Source
		{
			get
			{
				return this._Source;
			}
			set
			{
				this._Source = value;
			}
		}
		public string Message
		{
			get
			{
				return this._Message;
			}
			set
			{
				this._Message = value;
			}
		}
		public int HResult
		{
			get
			{
				return this._HResult;
			}
			set
			{
				this._HResult = value;
			}
		}
		public string HelpLink
		{
			get
			{
				return this._HelpLink;
			}
			set
			{
				this._HelpLink = value;
			}
		}
		public virtual object Get(int fieldPos)
		{
			switch (fieldPos)
			{
			case 0: return this.StackTrace;
			case 1: return this.Source;
			case 2: return this.Message;
			case 3: return this.HResult;
			case 4: return this.HelpLink;
			default: throw new AvroRuntimeException("Bad index " + fieldPos + " in Get()");
			};
		}
		public virtual void Put(int fieldPos, object fieldValue)
		{
			switch (fieldPos)
			{
			case 0: this.StackTrace = (System.String)fieldValue; break;
			case 1: this.Source = (System.String)fieldValue; break;
			case 2: this.Message = (System.String)fieldValue; break;
			case 3: this.HResult = (System.Int32)fieldValue; break;
			case 4: this.HelpLink = (System.String)fieldValue; break;
			default: throw new AvroRuntimeException("Bad index " + fieldPos + " in Put()");
			};
		}
	}
}
